### ISSUE TITLE
TYPO3 11 Support

### ISSUE THREAD

**Issue by tzeier** [supseven-at/mailchimp#43]
Will this Plugin be compatible with TYPO3 11?

**Comment by ingeniumdesign** [comment]
New infos? TYPO3 11 Update 👍

**Comment by h3nn3s** [comment]
You could test a newly submitted PR: #44

**Comment by phifa** [comment]
can we get this merged? is money needed?

**Comment by nabossha** [comment]
is there anything needed to merge the PR? would love to see a release
